apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceName }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: "{{ .Values.serviceName }}"
