apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.serviceName }}"
spec:
  tls:
  - hosts:
    - "{{ .Values.hostName}}"
    secretName: "{{ .Values.tls.secretName }}"

  rules:
  - host: "{{ .Values.hostName}}"
    http:
      paths:
      - path: /
        backend:
          serviceName: "{{ .Values.serviceName }}"
          servicePort: 80
